[project]
name = "hackerc"
version = "0.0.1"
description = "Transpilator jezyka HackerScript (.hsc) do Pythona"
requires-python = ">=3.10"
readme = "README.md"

[project.scripts]
hackerc = "hackerc.cli:main"

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["hackerc*"]
